import Data.Time
import qualified Data.Time as Time

-- Converts a string in the format YYYY-MM-DD to a Day
parseDay :: String -> Maybe Day
parseDay = parseTimeM True defaultTimeLocale "%Y-%m-%d"

-- Retrieves the DayOfWeek for a given Day using the qualified name
getDayOfWeek :: Day -> DayOfWeek
getDayOfWeek = Time.dayOfWeek

-- Main function to handle input and output
main :: IO ()
main = do
    putStrLn "Enter a date in YYYY-MM-DD format:"
    dateString <- getLine
    case parseDay dateString of
        Just day -> putStrLn $ "The day of the week is " ++ show (getDayOfWeek day)
        Nothing -> putStrLn "Invalid date format. Please use YYYY-MM-DD."


--Code generated by chat GPT 4.0
-- prompt was "can you make a haskell program that can tell me what day of the week it was on a given date"
